---
output: 
  bookdown::pdf_document2:
    citation_package: natbib
    keep_tex: false
    toc: false
    fig_caption: true
    latex_engine: pdflatex
    template: templates/svm-latex-ms.tex
bibliography: "references.bib"
header-includes:
  -  \usepackage{hyperref}
biblio-style: apalike
title: "AustralianPoliticians: A new dataset of all Australian federal, state, and colonial politicians"
thanks: "Our code and datasets are available at: https://github.com/RohanAlexander/australian_politicians. Comments on the `r format(Sys.time(), '%d %B %Y')` version of this paper are welcome at: rohan.alexander@utoronto.ca."
author:
- name: Rohan Alexander
  affiliation: University of Toronto
abstract: "Understanding who is, and has been, in parliament is a critical initial step for almost any type of quantitative analysis. Nonetheless, there is no publicly available comprehensive dataset of those who have been members of Australia's federal, state, and colonial parliaments. In this paper we introduce a new dataset - AustralianPoliticians - which contains daily data on the members of parliament for the Australian Federal Parliament, the six state parliaments, the two territory parliaments, and the preceeding colonial parliaments. We discuss the creation of this dataset, and then show its validity through various existing datasets and internal consistency tests. Finally, we discuss some extensions to this dataset. This dataset will be of use to those interested in quantitative analysis of Australian politics."
keywords: "Australian politics, dataset, comparative politics"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 12pt
# spacing: double
endnote: no
graphics: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

A critical first step for modern quantitative political analysis is a publicly available, comprehensive, dataset. In this paper we introduce one such dataset - AustralianPoliticians - which documents everyone who has been a member of any Australian federal, state, and/or colonial parliament. By bringing together various sources in this way, researchers can use this dataset to answer critical questions related to representation. Researchers can also build extensions to this dataset that focus on their particular interest. 

AustralianPoliticians is a record of everyone who has been a member of the Australian Federal Parliament (starting from 1901), the six state parliaments as well as their colonial predecessors, and the two territories. There are X unique people in the dataset, and the core dataset - `all` - provides basic biographical information about them. Related datasets are linked to this core dataset by a `uniqueID`, and deal with parliament and house, party, division, ministries, and finally translate the uniqueID into various other IDs used by other sources.

The datasets are up-to-date as of 1 July 2020, and will be maintained and updated on a quarterly basis, by the author for the next five years. The latest version of the datasets are publicly available via GitHub, with an annual version lodged with the Australian Data Archive.

These datasets represent a critical contribution to Australian political science. It is expected that they will be widely built on and expanded and we look forward to working with other researchers in this process.




# Summary statistics


# Creation and sources

## Australia

There have been X people elected to the Australian Federal Parliament from when it was established in 1901 through to 1 July 2020. This includes X people who did not take their seat either because of death or a nullified election.

## Queensland

## New South Wales

## Victoria

## Tasmania

## South Australia

## Western Australia

## Northern Territory

## Australian Capital Territory



# Validity

## Internal consistency

There are a variety of internal consistency measures that the dataset passes. These include: not having more members on any day than there are seats in parliament; X; and Y.

## Existing datasets



# Vignettes

In this section we walk through several vignettes to illustrate how to use the dataset. These vignettes include: the average age of parliaments and gender proportions over time.

## Average age of parliaments


## Gender proportions



# Extensions

The dataset represents a foundation that can be built on. In particular, 


# References



# Codebook


